# Generated by Django 6.0.7 on 2026-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('home', 'Home'), ('trending', 'Trending'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('food', 'Food'), ('education', 'Education'), ('sports', 'Sports'), ('health', 'Health'), ('science', 'Science')], default='home', max_length=30)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
