# Generated by Django 6.0.7 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(help_text='Name of the RSS feed source', max_length=255)),
                ('feed_url', models.URLField(help_text='URL of the RSS feed', unique=True)),
                ('category', models.CharField(choices=[('home', 'Home'), ('trending', 'Trending'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('food', 'Food'), ('education', 'Education'), ('sports', 'Sports'), ('health', 'Health'), ('science', 'Science')], default='home', help_text='Category where articles from this feed will be imported', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='When unchecked, this feed will not be fetched')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='Timestamp of the last successful fetch', null=True)),
                ('articles_count', models.IntegerField(default=0, help_text='Total articles imported from this feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Source',
                'verbose_name_plural': 'RSS Sources',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
